feat: Add quest_template_locale table
azerothcore/Keira3 pull request #3224
Opened 2024-12-30 00:32 UTC by vrachv

Add quest_template_locale table editor
I didnt add translations for the sidebar; english is currently used for all languages.

![image](https://github.com/user-attachments/assets/8a814b9b-c3db-4df1-9d44-f79edc83bf8b)

2024-12-31 11:01 UTC, Helias commented on libs/features/quest/src/quest-template-locale/quest-template-locale.component.ts
> +  readonly EMOTE = EMOTE;
```suggestion
  protected readonly EMOTE = EMOTE;
```

2024-12-31 11:05 UTC, Helias commented
Thanks for your PR, if all the tests pass I will do some manual test and merge it

2025-01-01 15:54 UTC, vrachv commented
I skipped the tests for this component, but I'll get to them soon

2025-01-04 21:54 UTC, vrachv commented
Note the changes in `multi-row-editor.service.ts`. I made this so that the ID is interpreted correctly when it is a string. There may be a better solution

2025-01-07 04:10 UTC, Exitare requested changes
Additionally to my review, a test is failing on my end. 

   - nx run keira-shared-base-abstract-classes:test

2025-01-07 04:10 UTC, Exitare commented on libs/features/quest/src/quest-template-locale/quest-template-locale.component.html
> +              <ngx-datatable-column name="Id" prop="ID" [minWidth]="80" [maxWidth]="150"></ngx-datatable-column>
This can be shortened to:
<ngx-datatable-column name="Id" prop="ID" [minWidth]="80" [maxWidth]="150"/>

2025-01-07 04:10 UTC, Exitare commented on libs/features/quest/src/quest-template-locale/quest-template-locale.component.html
> +              <ngx-datatable-column name="Locale" prop="locale" [minWidth]="200"></ngx-datatable-column>
See above

2025-01-07 04:10 UTC, Exitare commented on libs/features/quest/src/quest-template-locale/quest-template-locale.component.html
> +              <ngx-datatable-column name="Title" prop="Title" [minWidth]="200"></ngx-datatable-column>
See above

2025-01-07 04:10 UTC, Exitare commented on libs/features/quest/src/quest-template-locale/quest-template-locale.integration.spec.ts
> +        RouterTestingModule,
The RouterTestingModule is deprecated. Please switch it out if necessary.

2025-01-07 04:10 UTC, Exitare commented on libs/features/quest/src/quest-template-locale/quest-template-locale.integration.spec.ts
> +  let page: QuestTemplateLocalePage;
Please make sure to not use shared variables. 
See https://francescoborzi.github.io/ngx-page-object-model/docs/best-practices/avoid-shared-variables
It would be better to avoid having shared non-immutable variables across different tests and just initialise and return them in a setup function. 
For reference see:
https://github.com/azerothcore/Keira3/pull/3227/files

2025-01-12 17:41 UTC, Exitare commented
Tests passing, and working on my end :) Thanks for the update!

2025-01-19 18:35 UTC, Helias commented
While I was manually testing the PR I did the following updates:
- moved the QUEST_LOCALE option values under options/, the type files are only for types
- removed useless imports in the quest-template component
- replaced single-value-selector with generic-option-selector

The rest was ok, thanks for your contributions!

2025-01-19 19:16 UTC, Helias approved these changes

2025-01-19 19:16 UTC, merged